"""add account deletion fields

Revision ID: b43c4db2c8bd
Revises: a97efeb9a6f8
Create Date: 2026-08-13 16:19:51.244820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b43c4db2c8bd'
down_revision: Union[str, Sequence[str], None] = 'a97efeb9a6f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_deletion_requested', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('deletion_requested_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deletion_requested_at')
    op.drop_column('users', 'is_deletion_requested')
    # ### end Alembic commands ###
