"""add account schedule deletion field

Revision ID: d33cd89f8837
Revises: b43c4db2c8bd
Create Date: 2026-08-13 16:38:42.596617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd33cd89f8837'
down_revision: Union[str, Sequence[str], None] = 'b43c4db2c8bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deletion_scheduled_for', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deletion_scheduled_for')
    # ### end Alembic commands ###
