"""add company_id to jobs

Revision ID: f2311fef7898
Revises: 34428edcc56a
Create Date: 2026-08-08 17:00:32.898771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2311fef7898'
down_revision: Union[str, Sequence[str], None] = '34428edcc56a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'jobs', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'company_id')
    # ### end Alembic commands ###
